# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy server code
COPY . .

# Ensure unbuffered output and run the MCP server over stdio
ENV PYTHONUNBUFFERED=1
CMD ["python", "-u", "mcp_server.py"]
